version: '3.8'

services:
  assistant:
    build:
      context: .
      dockerfile: Dockerfile.assistant
    container_name: assistant
    ports:
      - "8000:8000"
    env_file: .env

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    depends_on:
      - assistant
    env_file: .env